#volumes:
#    ocserv-data: {}
services:
  openconnect:
    env_file:
      - openconnect.env
    image: eukhlg/openconnect:0.1.0
    restart: unless-stopped
    container_name: openconnect
    hostname: openconnect
    devices:
      - /dev/vhost-net:/dev/vhost-net
    volumes:
      - ./certs:/etc/openconnect/certs
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
